version: '3.3'
services:
  copilot-app:
    container_name: copilot-app
    image: registry.cn-hangzhou.aliyuncs.com/ripper/copilot-proxies:latest
    restart: always
    ports:
      - "1188:1188"
      - "443:443"
    environment:
      - PORT=1188
      - HTTPS_PORT=443
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./models.json:/root/models.json