version: '3'
services:
  nginx:
    image: registry.cn-hangzhou.aliyuncs.com/ripper/copilot-nginx:latest
    ports:
      - "443:443"
      - "1188:80"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"